"""Output data type vocabulary (#221 todo 2, #151): local keys, and EDAM ids when the generated subset is present.

Core code: the CSO plan, the runner and both semantics models read declarations through this package, and
removing the semantics pilot leaves it in place. ``output_types.yaml`` holds labhq's own keys and definitions.
``edam_subset.yaml`` (generated by ``scripts/edam_subset.py`` from a pinned EDAM release) maps each key to one
EDAM id or to ``unknown`` with a reason. Without the subset, or with a damaged one, every key stays local and
declarations still work; only the EDAM column is empty.

``Vocab.sha256`` is the interpretation version: a hash of what the keys mean (branch, definition, extensions)
and of the key → id mapping, never of timestamps, comments or line endings. Declarations carry it, and a
declaration made under another version is read as unknown rather than reinterpreted.
"""

from __future__ import annotations

import hashlib
import json
import logging
import re
from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import Path, PurePosixPath
from typing import Any

from ..yaml_unique import UniqueKeyError, load_yaml_unique

log = logging.getLogger("labhq.vocab")

VOCAB_DIR = Path(__file__).parent
LOCAL_FILE = "output_types.yaml"
SUBSET_FILE = "edam_subset.yaml"
BRANCHES = ("data", "format", "operation")
MAX_KEYS = 40          # local keys and distinct EDAM terms are each capped here (#151)
MAX_FILE_BYTES = 256 * 1024
KEY = re.compile(r"^[a-z][a-z0-9_]{1,31}$")
EXTENSION = re.compile(r"^\.[a-z0-9]{1,8}$")
EDAM_ID = re.compile(r"^(data|format|operation)_[0-9]{4}$")
SHA256 = re.compile(r"^[0-9a-f]{64}$")
EDAM_REASONS = ("no_candidate", "no_match", "ambiguous", "deprecated", "wrong_branch", "ancestor_missing",
                "ancestor_cycle", "ancestor_limit")
LOCAL = "local"
UNKNOWN = "unknown"


class VocabError(ValueError):
    """The local vocabulary could not be loaded. Messages name the file, never a path."""


@dataclass(frozen=True)
class Term:
    key: str
    branch: str
    extensions: tuple[str, ...] = ()
    edam_id: str | None = None        # None: local (no subset, or the script found no single term)
    edam_reason: str | None = None


@dataclass(frozen=True)
class Vocab:
    terms: Mapping[str, Term]
    local_sha256: str
    edam_sha256: str | None           # None when the subset is missing or was rejected
    edam_problem: str | None = None   # why the subset was rejected (a fixed code), None when loaded or absent

    @property
    def sha256(self) -> str:
        return _sha({"local": self.local_sha256, "edam": self.edam_sha256})

    def keys(self, branch: str) -> list[str]:
        return [k for k, t in self.terms.items() if t.branch == branch]

    def is_key(self, branch: str, value: Any) -> bool:
        term = self.terms.get(value) if isinstance(value, str) else None
        return term is not None and term.branch == branch

    def edam_id(self, key: str) -> str | None:
        term = self.terms.get(key)
        return term.edam_id if term else None

    @property
    def edam_ids(self) -> frozenset[str]:
        return frozenset(t.edam_id for t in self.terms.values() if t.edam_id)

    def format_of(self, path: str) -> str | None:
        """The format key whose extension the file name ends with, after peeling one ``.gz``; else None."""
        name = PurePosixPath(str(path).replace("\\", "/")).name.lower()
        if name.endswith(".gz"):
            name = name[:-3]
        suffix = PurePosixPath(name).suffix
        for key in self.keys("format"):
            if suffix and suffix in self.terms[key].extensions:
                return key
        return None

    def counts(self) -> dict[str, int]:
        """Local keys per branch and distinct EDAM terms, counted apart (each capped at MAX_KEYS)."""
        out = {b: len(self.keys(b)) for b in BRANCHES}
        return {**out, "keys": len(self.terms), "edam_terms": len(self.edam_ids)}


def _sha(value: Any) -> str:
    return hashlib.sha256(json.dumps(value, sort_keys=True, ensure_ascii=False, separators=(",", ":"))
                          .encode("utf-8")).hexdigest()


def _read(path: Path) -> Any:
    if path.stat().st_size > MAX_FILE_BYTES:
        raise VocabError(f"{path.name}: larger than {MAX_FILE_BYTES} bytes")
    try:
        return load_yaml_unique(path.read_text(encoding="utf-8"), path.name)
    except UniqueKeyError as exc:
        raise VocabError(str(exc)) from None
    except (OSError, UnicodeDecodeError) as exc:
        raise VocabError(f"{path.name}: {type(exc).__name__}") from None


def parse_local(data: Any, where: str = LOCAL_FILE) -> tuple[dict[str, Term], str]:
    """Check the local file's shape; return its terms and the hash of what they mean."""
    if not isinstance(data, Mapping) or data.get("version") != 1 or not isinstance(data.get("terms"), Mapping):
        raise VocabError(f"{where}: needs version: 1 and a terms mapping")
    terms: dict[str, Term] = {}
    meaning: dict[str, Any] = {}
    for key, body in data["terms"].items():
        if not isinstance(key, str) or not KEY.fullmatch(key):
            raise VocabError(f"{where}: key {key!r} is not a lower_snake name")
        if not isinstance(body, Mapping) or body.get("branch") not in BRANCHES:
            raise VocabError(f"{where}: {key} needs a branch of {list(BRANCHES)}")
        definition = body.get("definition")
        if not isinstance(definition, str) or not definition.strip():
            raise VocabError(f"{where}: {key} needs a definition")
        unknown = sorted(set(body) - {"branch", "definition", "extensions", "ok", "not", "review"})
        if unknown:
            raise VocabError(f"{where}: {key} has unknown fields {unknown}")
        extensions = body.get("extensions") or []
        if body["branch"] != "format" and extensions:
            raise VocabError(f"{where}: {key}: only format keys take extensions")
        if not isinstance(extensions, list) or not all(isinstance(e, str) and EXTENSION.fullmatch(e)
                                                       for e in extensions):
            raise VocabError(f"{where}: {key}: extensions are lower-case '.ext' strings")
        terms[key] = Term(key=key, branch=body["branch"], extensions=tuple(extensions))
        meaning[key] = {"branch": body["branch"], "definition": definition.strip(), "extensions": sorted(extensions)}
    if not terms or len(terms) > MAX_KEYS:
        raise VocabError(f"{where}: {len(terms)} keys; 1 to {MAX_KEYS} allowed")
    claimed: dict[str, str] = {}
    for term in terms.values():
        for ext in term.extensions:
            if ext in claimed:
                raise VocabError(f"{where}: extension {ext} belongs to both {claimed[ext]} and {term.key}")
            claimed[ext] = term.key
    return terms, _sha(meaning)


def parse_subset(data: Any, terms: Mapping[str, Term]) -> tuple[dict[str, tuple[str | None, str | None]], str]:
    """Check the generated subset against the local keys. Raises ValueError with a fixed code."""
    if not isinstance(data, Mapping):
        raise ValueError("subset_shape")
    source = data.get("source")
    if (not isinstance(source, Mapping) or not isinstance(source.get("release"), str)
            or not SHA256.fullmatch(str(source.get("sha256") or "")) or not isinstance(source.get("license"), str)
            or not isinstance(source.get("url"), str)):
        raise ValueError("subset_source")
    body = data.get("terms")
    if not isinstance(body, Mapping) or set(body) != set(terms):
        raise ValueError("subset_keys_mismatch")
    mapping: dict[str, tuple[str | None, str | None]] = {}
    for key, entry in body.items():
        if not isinstance(entry, Mapping) or entry.get("branch") != terms[key].branch:
            raise ValueError("subset_branch_mismatch")
        edam = entry.get("id")
        if edam == UNKNOWN:
            if entry.get("reason") not in EDAM_REASONS:
                raise ValueError("subset_reason")
            mapping[key] = (None, entry["reason"])
        elif isinstance(edam, str) and EDAM_ID.fullmatch(edam) and edam.split("_", 1)[0] == terms[key].branch:
            mapping[key] = (edam, None)
        else:
            raise ValueError("subset_id")
    if len({m[0] for m in mapping.values() if m[0]}) > MAX_KEYS:
        raise ValueError("subset_too_many_terms")
    interpretation = {"release": source["release"], "sha256": source["sha256"],
                      "terms": {k: {"id": v[0] or UNKNOWN, "reason": v[1]} for k, v in sorted(mapping.items())}}
    return mapping, _sha(interpretation)


def load(directory: Path | None = None) -> Vocab:
    """Load the local keys (required) and the EDAM subset (optional). A bad subset never fails the load."""
    directory = Path(directory) if directory is not None else VOCAB_DIR
    try:
        terms, local_sha = parse_local(_read(directory / LOCAL_FILE))
    except FileNotFoundError:
        raise VocabError(f"{LOCAL_FILE}: missing") from None
    edam_sha = problem = None
    subset_path = directory / SUBSET_FILE
    if subset_path.exists():
        try:
            mapping, edam_sha = parse_subset(_read(subset_path), terms)
            terms = {k: Term(t.key, t.branch, t.extensions, *mapping[k]) for k, t in terms.items()}
        except VocabError:
            problem = "subset_unreadable"
        except ValueError as exc:
            problem = str(exc)
        if problem:
            log.warning("EDAM subset ignored (%s); output type keys stay local", problem)
    return Vocab(terms=terms, local_sha256=local_sha, edam_sha256=edam_sha, edam_problem=problem)


_CACHE: dict[str, Vocab | None] = {}


def current() -> Vocab | None:
    """The packaged vocabulary, loaded once per process; None (with one warning) when it cannot load.

    A missing or broken vocabulary turns declarations off; it never fails a plan, a task or the gateway."""
    if "v" not in _CACHE:
        try:
            _CACHE["v"] = load()
        except (VocabError, OSError) as exc:
            log.warning("output type vocabulary unavailable (%s); output type declarations stay off", exc)
            _CACHE["v"] = None
    return _CACHE["v"]


def reset_cache() -> None:
    _CACHE.clear()
